name: Puma

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Test on ruby ${{ matrix.ruby_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby_version: [2.4.x,2.5.x,2.6.x] # 2.2 is not currently offered, 2.3 not on windows
        os: [ubuntu-latest] # MacOS is bugged r/n, see: https://github.com/actions/setup-ruby/issues/9, windows doesnt want to run bundle install for some reason

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: actions/setup-ruby@master
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Compiles extensions
      run: |
        bundle exec rake compile
    - name: Build and test with Rake
      env:
        CI: true
        TESTOPTS: -v
      run: |
        bundle exec rake
